spring:
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.globally_quoted_identifiers: true
  profiles:
    active: dev
#  datasource:
#    initialization-mode: always
#    schema: classpath*:database/initDB.sql
#    data: classpath*:database/populateDB.sql


#spring.datasource.schema=classpath*:database/initDB.sql
#spring.datasource.data=classpath*:database/populateDB.sql

jwt:
  accessToken:
    # Срок действия в днях
    expiration: 7
    # Название куки
    cookieName: accessToken
  refreshToken:
    # Срок действия в днях
    expiration: 15
    # Название куки
    cookieName: refreshToken
  secret: 9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(H+MbQeThWmZq4

