CREATE TABLE IF NOT EXISTS students
(
    ID    VARCHAR(255) PRIMARY KEY ,
    NAME  VARCHAR(200) NOT NULL ,
    SUBJECT  VARCHAR(200) NOT NULL ,
    TOPIC VARCHAR(254) NOT NULL ,
    TYPE VARCHAR(20)  NOT NULL,
    POINT SERIAL NOT NULL
);
